---
- name: Play to deploy a CentOS7 instance in Oracle Cloud Infrastructure (OCI)
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    ansible_compartment_id: ocid1.tenancy.oc1..aaaaaaaabtoullhyh6mzpinqgtpu2ovhrlt3rlcya4ydxdewjtkigar2xjca

  tasks:
    - name: Create a Virtual Cloud Network (VCN)
      oci_network_vcn:
        compartment_id: "{{ ansible_compartment_id }}"
        display_name: "ansible_vcn"
        cidr_block: "10.1.0.0/16"
        dns_label: "sreejithvcn"
      register: vcn_result
    - set_fact:
        vcn_id: "{{ vcn_result.vcn.id }}"

    - name: Create a new Internet Gateway (IG)
      oci_network_internet_gateway:
        compartment_id: "{{ ansible_compartment_id }}"
        vcn_id: "{{ vcn_id }}"
        name: "ansible_ig"
        is_enabled: 'yes'
        state: 'present'
      register: ig_result
    - set_fact:
        ig_id: "{{ ig_result.internet_gateway.id }}"

    - name: Create Route Table (RT) to connect Internet Gateway (IG) to the VCN
      oci_network_route_table:
        compartment_id: "{{ ansible_compartment_id }}"
        vcn_id: "{{ vcn_id }}"
        name: "ansible_rt"
        route_rules: 
          - cidr_block: "0.0.0.0/0"
            network_entity_id: "{{ ig_id }}"
        state: 'present'
      register: rt_result
    - set_fact:
        rt_id: "{{ rt_result.route_table.id }}"

    - name: Create a Security List for allowing access to the CentOS Public Instance
      oci_network_security_list:
        name: "ansible_security_list"
        compartment_id: "{{ ansible_compartment_id }}"
        vcn_id: '{{ vcn_id }}'
        ingress_security_rules:
          - source: "0.0.0.0/0"
            protocol: "6"
            tcp_options:
              destination_port_range:
                min: "22"
                max: "22"

        egress_security_rules:
          - destination: "0.0.0.0/0"
            protocol: "6"
            tcp_options:
              destination_port_range:
                min: "22"
                max: "22"
      register: sl_result
    - set_fact:
        instance_security_list_ocid: "{{ sl_result.security_list.id }}"

    - name: Create a subnet to host the public instance. Link security_list and route_table.
      oci_network_subnet:
        availability_domain: "AjjE:AP-HYDERABAD-1-AD-1"
        cidr_block: "10.1.1.0/24"
        compartment_id: "{{ ansible_compartment_id }}"
        display_name: "ansible_subnet"
        prohibit_public_ip_on_vnic: false
        route_table_id: "{{ rt_id }}"
        security_list_ids: [ "{{ instance_security_list_ocid }}" ]
        vcn_id: '{{ vcn_id }}'
        dns_label: "sreejithsubnet"
      register: subnet_result
    - set_fact:
       instance_subnet_id: "{{ subnet_result.subnet.id }}"
   
    - name: Launch an instance
      oci_compute_instance:
        availability_domain: "AjjE:AP-HYDERABAD-1-AD-1"
        compartment_id: "{{ ansible_compartment_id }}"
        name: "ansible-centos7"
        source_details:
          source_type: image
          image_id: "ocid1.image.oc1.ap-hyderabad-1.aaaaaaaailhvdxrn2lnwityiuydzfjjz66ibpht5v65r6p7mnf3kigwng2aa"
        shape: "VM.Standard.E2.1.Micro"
        create_vnic_details:
          assign_public_ip: True
          hostname_label: "sreejithinstance"
          subnet_id: "{{ instance_subnet_id }}"
        metadata:
          ssh_authorized_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwI5wLk+UJWmioSFZYzTocdzduRAJOrAzg6BUeON32E75Nebt+iimhSxGTuMX/a+aisCuxqDp6xiMGTLVj81oFiD31PJJ14pekTPPXO+BKjf9a2hFFg+YTibwa98vj0dcLoFL0K9wNH4taMprJtwKreRZ7CeFhfZSaVh6NfFJeX7QgneDFMUfJMym3vBqIzUXWbqwJZb5wHP0PPd9XaW0kF3jbnxi8xvGQ62C8MpcMvx86IxB3pAERSpiItXR4EzeqcKB5SYobfYHdl9AcdehgHl+kjYmA51z5cIWpcTzVNJmBZXqbFhnhN7d94NK5dnp7PFgD1NBiNnleCULrv+LslE1BzN3FOEFAEag9VliwvZdXUVc4Y0hI4I9dY1tKu4plxYOMNd6DhVKkIMpZAFxmYO9bWh0n+l3cy6N1s6PY8ToPdE3qgB8EA6VKYc70haabHgrZTAufZ4skrc8Uh44BX+eDN6+A7uTrPKoe/vYct6OP4olST/n0un+hjsG39UE= sanujan@fedora.mj0vy.org"
      register: instance_result
    - set_fact:
        centos_instance_id: "{{ instance_result.instance.id }}"

    - name: Get the Virtual NIC attachment details of the CentOS Instance
      oci_compute_vnic_attachment_facts:
        compartment_id: "{{ ansible_compartment_id }}"
        instance_id: "{{ centos_instance_id }}"
      register: vnic_attachment_result

    - name: Get details of the Virtual NIC associated with the public ip
      oci_network_vnic_facts:
        id: "{{ vnic_attachment_result.vnic_attachments[0].vnic_id }}"
      register: vnic_result
    - set_fact:
        centos_instance_public_ip: "{{vnic_result.vnic.public_ip}}"

    - name: Print the public ip of the CentOS7 Instance
      debug:
        msg: "The CentOS7 Instance is available at the public ip: {{ centos_instance_public_ip }}"
